version: '3.9'

services:
  postgres:
    image: postgres:16.1
    container_name: poketrade-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  centrifugo:
    container_name: poketrade-centrifugo
    image: centrifugo/centrifugo:v5.2.0
    environment:
      CENTRIFUGO_PORT: ${CENTRIFUGO_PORT}
      CENTRIFUGO_ALLOWED_ORIGINS: ${CENTRIFUGO_ALLOWED_ORIGINS}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_TOKEN_HMAC_SECRET_KEY}
      CENTRIFUGO_NAMESPACES: "[{\"name\": \"personal\"}]"

      CENTRIFUGO_ADMIN: "true"
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - ${CENTRIFUGO_PORT}:${CENTRIFUGO_PORT}

  app:
    build: ./
    container_name: poketrade-app
    environment:
      HOST: app
      PORT: ${PORT}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      CENTRIFUGO_API_URL: http://centrifugo:${CENTRIFUGO_PORT}/api
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_TOKEN_HMAC_SECRET_KEY}
    depends_on:
      - postgres
      - centrifugo
    links:
      - postgres
      - centrifugo
    ports:
      - ${PORT}:${PORT}
