name: Continuous Integration

on:
  push

# TODO: Add tests
jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
